steps:
  # ---------------------------
  # 1) Build + Deploy agent-adk
  # ---------------------------
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/lexia-agent-dpk:$SHORT_SHA", "."]
    dir: "services/agent-adk"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/lexia-agent-dpk:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run","deploy","lexia-agent-dpk",
        "--image","gcr.io/$PROJECT_ID/lexia-agent-dpk:$SHORT_SHA",
        "--region","southamerica-east1",
        "--platform","managed",
        "--allow-unauthenticated",
        "--set-env-vars",
        "DPK_SHARED_SECRET=${_DPK_SHARED_SECRET},AGENT_INSTRUCTION=${_AGENT_INSTRUCTION},GEMINI_MODEL=${_GEMINI_MODEL}"
      ]

  # ---------------------------
  # 2) Build + Deploy webhook-node
  # ---------------------------
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/lexia-webhook-wa:$SHORT_SHA", "."]
    dir: "services/webhook-node"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/lexia-webhook-wa:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run","deploy","lexia-webhook-wa",
        "--image","gcr.io/$PROJECT_ID/lexia-webhook-wa:$SHORT_SHA",
        "--region","southamerica-east1",
        "--platform","managed",
        "--allow-unauthenticated",
        "--memory","512Mi",
        "--timeout","3600",
        "--set-env-vars",
        "DPK_AGENT_URL=${_DPK_AGENT_URL},DPK_SHARED_SECRET=${_DPK_SHARED_SECRET},VERIFY_TOKEN=${_VERIFY_TOKEN},WHATSAPP_ACCESS_TOKEN=${_WHATSAPP_ACCESS_TOKEN},WHATSAPP_PHONE_NUMBER_ID=${_WHATSAPP_PHONE_NUMBER_ID},WHATSAPP_BUSINESS_ACCOUNT_ID=${_WHATSAPP_BUSINESS_ACCOUNT_ID},DATABASE_URL=${_DATABASE_URL},ASAAS_API_KEY=${_ASAAS_API_KEY},ASAAS_WEBHOOK_TOKEN=${_ASAAS_WEBHOOK_TOKEN},INFOSIMPLES_API_KEY=${_INFOSIMPLES_API_KEY}"
      ]

  # ---------------------------
  # 3) Build + Deploy portal
  # ---------------------------
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/lexia-portal:$SHORT_SHA", "."]
    dir: "services/portal"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/lexia-portal:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run","deploy","lexia-portal",
        "--image","gcr.io/$PROJECT_ID/lexia-portal:$SHORT_SHA",
        "--region","southamerica-east1",
        "--platform","managed",
        "--allow-unauthenticated",
        "--memory","1Gi",
        "--timeout","3600",
        "--set-env-vars",
        "DPK_AGENT_URL=${_DPK_AGENT_URL},DPK_SHARED_SECRET=${_DPK_SHARED_SECRET},DATABASE_URL=${_DATABASE_URL}"
      ]

substitutions:
  _DPK_AGENT_URL: "https://REPLACE_WITH_AGENT_ADK_URL"
  _DPK_SHARED_SECRET: "REPLACE_WITH_STRONG_SECRET"
  _AGENT_INSTRUCTION: "REPLACE_WITH_AGENT_INSTRUCTION"
  _GEMINI_MODEL: "gemini-2.5-pro"
  _VERIFY_TOKEN: "REPLACE_WITH_VERIFY_TOKEN"
  _WHATSAPP_ACCESS_TOKEN: "REPLACE_WITH_WHATSAPP_ACCESS_TOKEN"
  _WHATSAPP_PHONE_NUMBER_ID: "REPLACE_WITH_WHATSAPP_PHONE_NUMBER_ID"
  _WHATSAPP_BUSINESS_ACCOUNT_ID: "REPLACE_WITH_WHATSAPP_BUSINESS_ACCOUNT_ID"
  _DATABASE_URL: "REPLACE_WITH_DATABASE_URL"
  _ASAAS_API_KEY: "REPLACE_WITH_ASAAS_API_KEY"
  _ASAAS_WEBHOOK_TOKEN: "REPLACE_WITH_ASAAS_WEBHOOK_TOKEN"
  _INFOSIMPLES_API_KEY: "REPLACE_WITH_INFOSIMPLES_API_KEY"

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "3600s"
